'use strict';
// Real Edge, production page, synthetic microphone/video and a fake native bridge.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const out=path.join(root,'work','speaker-review');fs.mkdirSync(out,{recursive:true});
const audio=Buffer.alloc(44+10*16000*2);audio.write('RIFF');audio.writeUInt32LE(audio.length-8,4);audio.write('WAVEfmt ',8);audio.writeUInt32LE(16,16);audio.writeUInt16LE(1,20);audio.writeUInt16LE(1,22);audio.writeUInt32LE(16000,24);audio.writeUInt32LE(32000,28);audio.writeUInt16LE(2,32);audio.writeUInt16LE(16,34);audio.write('data',36);audio.writeUInt32LE(audio.length-44,40);for(let i=0;i<160000;i++)audio.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*220/16000)*1500),44+i*2);
const speakers={available:true,transcript_id:'synthetic-v1',selected_id:0,suggested_id:0,source:'auto',confidence:'recommended',reason:'duration_and_level',speakers:[{speaker_id:0,speech_seconds:8,speech_share:.8,median_dbfs:-18,sample_start:2,sample_end:2.5},{speaker_id:1,speech_seconds:2,speech_share:.2,median_dbfs:-30,sample_start:6,sample_end:6.5}]};
const data={title:'合成说话人验证',game:'合成测试',id:'speaker-test',test:true,desktop:true,video:'/demo.mp4',narration:'/microphone.wav',segments:[{start:2,end:5,text:'这是合成记录者的讲述。',speaker_id:0},{start:6,end:8,text:'这是另一位合成说话人。',speaker_id:1},{start:8,end:9,text:'这是未区分说话人的原话。'}],speakers,transcription:{state:'ready'},inputs:{state:'disabled',intervals:[],gaps:[],duration:10}};
function pageHtml(url){const d=structuredClone(data);if(url.includes('legacy')){delete d.speakers;d.segments.forEach(s=>delete s.speaker_id);}if(url.includes('portable'))d.desktop=false;const values={TITLE:d.title,DATA:JSON.stringify(d),CSS:read('ui/review.css'),JS:read('ui/review.js'),PLYR_CSS:read('ui/vendor/plyr/plyr.css'),PLYR_JS:read('ui/vendor/plyr/plyr.min.js'),PLYR_SVG:read('ui/vendor/plyr/plyr.svg'),LICENSE:'Synthetic speaker test'};return read('player.html').replace(/%%([A-Z_]+)%%/g,(_,k)=>values[k]);}
const media=fs.readFileSync(path.join(root,'docs/prototypes/input-review/demo.mp4'));
const server=http.createServer((req,res)=>{const bytes=req.url==='/demo.mp4'?media:req.url==='/microphone.wav'?audio:null;res.setHeader('Content-Type',bytes?(req.url.endsWith('wav')?'audio/wav':'video/mp4'):'text/html; charset=utf-8');res.end(bytes||pageHtml(req.url));});
const evidence={scope:'Synthetic browser-only speaker acceptance; no real cloud or speaker-recognition accuracy claim.',checks:[],errors:[]};let browser;
async function main(){
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>evidence.errors.push(String(e)));
 await page.addInitScript(d=>{
  window.__snapshot=structuredClone(d);window.__saved=[];window.__fail=false;
  window.pywebview={api:{ready:async()=>({ok:true}),get_layout:async()=>({ok:true,data:{}}),save_layout:async()=>({ok:true}),get_snapshot:async()=>({ok:true,data:window.__snapshot}),
   set_recorder_speaker:async(id,identity,auto)=>{
    if(window.__fail)return {ok:false,error:'合成保存失败'};
    if(identity!==window.__snapshot.speakers.transcript_id)return {ok:false,error:'逐字稿已更新，请重新选择。'};
    window.__saved.push([id,identity,auto]);
    if(auto||id!==window.__snapshot.speakers.selected_id)window.__snapshot.speakers={...window.__snapshot.speakers,selected_id:auto?window.__snapshot.speakers.suggested_id:id,source:auto?'auto':'manual'};
    return {ok:true,data:window.__snapshot.speakers};
   }
  }};
 },data);
 const check=async(name,fn)=>{await fn();evidence.checks.push({name,pass:true});};
 await page.goto(origin);await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
 await check('quiet default recorder control stays in transcript tools without hiding any words',async()=>{assert.equal(await page.locator('#recorderLabel').textContent(),'记录者：默认');assert.equal(await page.locator('#speakerSummary').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await page.locator('.line').count(),3);assert.match(await page.locator('.line').nth(0).textContent(),/记录者 · 自动/);assert.match(await page.locator('.line').nth(1).textContent(),/说话人 1/);assert.match(await page.locator('.line').nth(2).textContent(),/说话人未区分/);await page.locator('#inputTab').click();assert.equal(await page.locator('#speakerSummary').isVisible(),false);await page.locator('#transcriptTab').click();assert.equal(await page.locator('#speakerSummary').isVisible(),true);await page.screenshot({path:path.join(out,'recorder-control-1440.png')});});
 await check('unchanged default save stays automatic and both compact controls open the same explanation',async()=>{await page.locator('#speakerSummary').click();assert.match(await page.locator('#speakerCurrent').textContent(),/80%/);assert.match(await page.locator('#speakerPreprocessHint').textContent(),/agent 重新预处理/);await page.locator('#saveSpeaker').click();await page.waitForFunction(()=>!document.querySelector('#speakerDialog').open);assert.equal(await page.locator('#recorderLabel').textContent(),'记录者：默认');await page.locator('.line').first().click();await page.waitForFunction(()=>!document.querySelector('#currentQuoteSpeakerControl').hidden);await page.locator('video').evaluate(v=>v.pause());await page.locator('#currentQuoteSpeakerControl').click();assert.match(await page.locator('#speakerCurrent').textContent(),/80%/);await page.locator('#closeSpeakers').click();});
 await page.locator('#speakerSummary').click();
 await check('dialog gives duration, relative volume and isolated microphone preview',async()=>{assert.match(await page.locator('#speakerChoices').textContent(),/00:00:08.*80%/);await page.getByRole('button',{name:'试听说话人 0'}).click();await page.waitForFunction(()=>document.querySelector('#speakerAudio').currentTime>=2.2);assert.ok(await page.locator('#speakerAudio').evaluate(a=>a.src.endsWith('/microphone.wav')));assert.equal(await page.locator('video').evaluate(v=>v.paused),true);await page.waitForFunction(()=>document.querySelector('#speakerAudio').paused);});
 await check('keyboard selection and manual save keep playback still and label the selected recorder',async()=>{await page.locator('input[name=recorderSpeaker][value="1"]').check();await page.locator('#saveSpeaker').focus();const before=await page.locator('video').evaluate(v=>v.currentTime);await page.keyboard.press('Space');await page.waitForFunction(()=>!document.querySelector('#speakerDialog').open);assert.equal(await page.locator('video').evaluate(v=>v.currentTime),before);assert.match(await page.locator('#recorderLabel').textContent(),/说话人 1/);assert.match(await page.locator('.line').nth(0).textContent(),/说话人 0/);assert.match(await page.locator('.line').nth(1).textContent(),/记录者 · 已确认/);assert.deepEqual(await page.evaluate(()=>window.__saved.at(-1)),[1,'synthetic-v1',false]);});
 await check('native failure keeps previous identity and an actionable open dialog',async()=>{await page.locator('#speakerSummary').click();await page.locator('input[value="0"][name=recorderSpeaker]').check();await page.evaluate(()=>window.__fail=true);await page.locator('#saveSpeaker').click();await page.waitForFunction(()=>!document.querySelector('#speakerError').hidden);assert.equal(await page.locator('#speakerDialog').evaluate(d=>d.open),true);assert.match(await page.locator('#recorderLabel').textContent(),/说话人 1/);await page.evaluate(()=>window.__fail=false);await page.locator('#closeSpeakers').click();});
 await check('can explicitly leave recorder unassigned and restore automatic recommendation',async()=>{await page.locator('#speakerSummary').click();await page.locator('input[value=none]').check();await page.locator('#saveSpeaker').click();await page.waitForFunction(()=>document.querySelector('#recorderLabel').textContent==='记录者：未指定');await page.locator('#speakerSummary').click();await page.locator('#autoSpeaker').click();await page.waitForFunction(()=>document.querySelector('#recorderLabel').textContent==='记录者：默认');});
 await check('speaker-only snapshot update reaches transcript badges',async()=>{await page.evaluate(()=>window.__snapshot.speakers={...window.__snapshot.speakers,selected_id:1,source:'manual'});await page.waitForFunction(()=>document.querySelectorAll('.line .speaker-tag')[1].textContent.includes('已确认'));});
 await check('dialog remains usable at a narrow window and dark theme',async()=>{await page.setViewportSize({width:560,height:700});await page.locator('#themeButton').click();await page.locator('#speakerSummary').click();const rect=await page.locator('#speakerDialog').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=561&&rect.y>=0&&rect.y+rect.height<=701);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'speaker-dialog-dark-560.png')});await page.locator('#closeSpeakers').click();});
 await check('portable changes clearly stay in this view',async()=>{await page.setViewportSize({width:1440,height:900});await page.goto(origin+'/portable');await page.locator('#speakerSummary').click();assert.match(await page.locator('#speakerSaveScope').textContent(),/仅用于本次回看/);await page.locator('input[value="1"][name=recorderSpeaker]').check();await page.locator('#saveSpeaker').click();assert.match(await page.locator('#recorderLabel').textContent(),/说话人 1/);assert.equal(await page.evaluate(()=>window.__saved.length),0);});
 await check('legacy files keep their original unlabelled layout',async()=>{await page.goto(origin+'/portable-legacy');assert.equal(await page.locator('#speakerSummary').isHidden(),true);assert.equal(await page.locator('.line .speaker-tag:visible').count(),0);assert.equal(await page.locator('.line').count(),3);});
 await page.goto(origin);await page.locator('#speakerSummary').click();await page.screenshot({path:path.join(out,'speaker-dialog-1440.png')});
 assert.deepEqual(evidence.errors,[]);evidence.pass=true;
}
main().catch(error=>{evidence.error=String(error.stack||error);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify(evidence,null,2));if(browser)await browser.close();server.close();console.log(JSON.stringify(evidence));});
